version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # แมปพอร์ตจาก container ไปยัง host
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=peempleng123
      - DB_NAME=ku-toilet
      - DB_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: peempleng123
      POSTGRES_DB: ku-toilet
    ports:
      - "5432:5432" # แมปพอร์ตจาก container ไปยัง host
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  postgres_data: